[package]
name = "kernel"
version = "0.0.0"

[lib]
path = "main.rs"
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]